#服务端设置
server:
  port: 80
  #ip,域名都设置在address
  address: 172.16.0.10
  #address: localhost
  session:
    timeout: 30
  tomcat:
    max-threads: 0
    uri-encoding: UTF-8
#HTTP编码设置
spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
#日志设置
logging:
  # 日志文件,绝对路径或相对路径（可以设置文件名称）
  file: /tmp/ragdollhouselog/log.log
  #file: D:/360Downloads/log.log
  level:
    com:
      favorites: DEBUG
    org:
      springframework:
        web: DEBUG
