#服务端设置
server:
  port: 80
  #ip,域名都设置在address
  #address: 172.16.0.10
  address: 10.41.0.77
  tomcat:
    max-threads: 0
    uri-encoding: UTF-8

spring:
  datasource:
    #url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8
    #username: test
    #password: test
    url: jdbc:mysql://111.230.51.227:3306/ragdoll?characterEncoding=utf8&useSSL=false
    username: lishaoxiong
    password: lsx123456LSX
#HTTP编码设置
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
#配置thymeleaf模板路径
  mvc:
    view:
      prefix: /templates/
      suffix: .html
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
#日志设置
logging:
  #日志文件,绝对路径或相对路径（可以设置文件名称）
  file: /tmp/ragdollhouselog/log.log
  #file: D:/360Downloads/log.log
  level:
    club:
      ragdollhouse:
        #数据库操作打印日志
        Mapper: debug
    org:
      springframework:
        web: debug


#ueditor参数配置
ueditor:
  #图片编辑暂存路径
  #path: C:/ueditor_img/testuedit_image
  path: /usr/staticfile/file/editorimg
  #编辑图片预览地址
  #viewurl: http://127.0.0.1:8099/testuedit_image/
  viewurl: http://ragdollhouse.club:8099/file/editorimg/


#首页图片上传路径
homepage:
  #上传路径
  path: C:/ueditor_img/indexpage
  #path: /usr/staticfile/file/indexpage