#服务端设置
server:
  port: 80
  #ip,域名都设置在address
  #address: 172.16.0.10
  address: 10.14.6.85
  tomcat:
    max-threads: 0
    uri-encoding: UTF-8

spring:
  datasource:
    #url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8
    #username: test
    #password: test
    url: jdbc:mysql://111.230.51.227:3306/ragdoll?characterEncoding=utf8&useSSL=false
    username: lishaoxiong
    password: lsx123456LSX
#HTTP编码设置
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
#配置thymeleaf模板路径
  mvc:
    view:
      prefix: /templates/
      suffix: .html
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
#日志设置
logging:
  # 日志文件,绝对路径或相对路径（可以设置文件名称）
  file: /tmp/ragdollhouselog/log.log
  #file: D:/360Downloads/log.log
  level:
    club:
      ragdollhouse:
        Mapper: debug
    org:
      springframework:
        web: debug
